---
title: "p8105_hw3_wz2506"
author: "Weiran Zhang"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(viridis)
library(forcats)
```


##Problem 1

```{r}
library(p8105.datasets)
data("instacart") ##Load data instacart

```

```{r}
##How many aisle in total
max(pull(instacart, aisle_id))
min(pull(instacart, aisle_id))

##wrangle the table to aisle_id and number of items ordered from each aisle
instacart = instacart %>%
  group_by(aisle_id) %>%
  summarize(n = n())


```
`Range of aisle_id is from 1 to 134, so there are 134 aisles in total.`

```{r}
##dataset of aisle_id and number of items ordered from the aisles over 10000 to check for the aisle with the most items ordered from
instacart %>%
  mutate(
    large = case_when(
      n > 10000 ~ "large",
      n <= 10000 ~ "not_large",
      TRUE     ~ ""
    )) %>%
  filter(large == "large") %>%
  group_by(aisle_id, large)

##plot of number of items ordered from each aisle for items number over 10000
instacart %>%
  mutate(
    large = case_when(
      n > 10000 ~ "large",
      n <= 10000 ~ "not_large",
      TRUE     ~ ""
    )) %>%
  filter(large == "large") %>%
  group_by(aisle_id, large) %>%
  ggplot(aes(x = aisle_id, y = n)) +
  geom_point()

```

`From the dataset of aisle_id and number of items over 10000, we can see that the aisle with aisle_id = 83 is the aisle with most items oredered from.`

```{r}
##Table of three most popular items in the three specific aisles
library(p8105.datasets)
data("instacart")
instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle, product_name) %>%
  summarize(n = n()) %>%
  filter(min_rank(desc(n)) < 4 )%>%
  knitr::kable(digits = 1)

```

```{r}

##Table of mean hour of day
library(p8105.datasets)
data("instacart")
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  mutate(order_dow = replace(order_dow, order_dow == '0', 'Sunday'),
         order_dow = replace(order_dow, order_dow == '1', 'Monday'),
         order_dow = replace(order_dow, order_dow == '2', 'Tuesday'),
         order_dow = replace(order_dow, order_dow == '3', 'Wednesday'),
         order_dow = replace(order_dow, order_dow == '4', 'Thursday'),
         order_dow = replace(order_dow, order_dow == '5', 'Friday'),
         order_dow = replace(order_dow, order_dow == '6', 'Saturnday'),
  ) %>%
  group_by(product_name, order_dow) %>%
  summarize(meanhour = mean(order_hour_of_day)) %>%
  pivot_wider(
    id_cols = c(product_name, order_dow, meanhour),
    names_from = order_dow,
    values_from = meanhour) %>%
  knitr::kable(digits = 1)

```

##Problem 2

```{r}
##Load BRFSS dataset
library(p8105.datasets)
data("brfss_smart2010")

```

```{r}

##Data cleaning following the instructions
tidy_data = brfss_smart2010 %>%
  filter(Topic == "Overall Health", 
         Response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>%
  mutate(Response = as.factor(Response)) %>%
  mutate(Response = forcats::fct_relevel(Response, c("Excellent","Very Good","Good","Fair","Poor"))) %>%
  arrange(Response)
```

```{r}

##states that observed at 7 or more locations in year 2002
brfss_smart2010 %>%
  filter(Topic == "Overall Health", 
         Response %in% c("Excellent", "Very good", "Good", "Fair", "Poor"), 
         Year == "2002") %>%
  group_by(Locationdesc) %>%
  separate(Locationdesc, c("state","county"), sep = "-") %>%
  group_by(state) %>%
  summarize(n = n()) %>%
  mutate(
    observed = case_when(
      n >= 7 ~ "observed",
      n < 7 ~ "not_observed",
      TRUE     ~ ""
    )) %>%
  filter(observed == "observed") %>%
  group_by(observed)

##states that observed at 7 or more locations in year 2010
brfss_smart2010 %>%
  filter(Topic == "Overall Health", 
         Response %in% c("Excellent", "Very good", "Good", "Fair", "Poor"), 
         Year == "2010") %>%
  group_by(Locationdesc) %>%
  separate(Locationdesc, c("state","county"), sep = "-") %>%
  group_by(state) %>%
  summarize(n = n()) %>%
  mutate(
    observed = case_when(
      n >= 7 ~ "observed",
      n < 7 ~ "not_observed",
      TRUE     ~ ""
    )) %>%
  filter(observed == "observed") %>%
  group_by(observed)

```

```{r}
##“spaghetti” plot
brfss_smart2010 %>%
  select(Year, Response, Locationabbr, Data_value) %>%
  filter(Response == "Excellent") %>%
  group_by(Locationabbr, Year) %>%
  summarize(mean_data = mean(Data_value)) %>%
  ggplot(aes(x = Year, y = mean_data, color = Locationabbr)) +
  geom_point() + geom_line() 

```

```{r}

##Two-panel plots showing distribution of data_value
tidy_data %>%
  filter(Year %in% c(2006, 2010), 
         Locationabbr == "NY") %>%
  ggplot(aes(x = Response, y = Data_value)) +
  geom_boxplot() + 
  facet_grid(~Year) +
  viridis::scale_fill_viridis(discrete = TRUE)
```




